# GET http://localhost:4000/user-api/users

# POST http://localhost:4000/user-api/users
# Content-Type: application/json

# {
#     "height":184,
#     "weight": 77,
#     "age": 20,
#     "desiredweight":74,
#     "gender":"Male",
#     "firstName": "Rishi",
#     "lastName": "Varma",
#     "email": "rishi@gmail.com",
#     "profileImageUrl":"dfgfdgdf"
# }


PUT http://localhost:4000/user-api/users/email
Content-Type: application/json

{
    "_id": "67d3d844b6633e740db28d6b",
    "height":184,
    "weight": 77,
    "age": 20,
    "desiredweight":71,
    "gender":"Male",
    "firstName": "Rishi",
    "lastName": "Varma",
    "email": "rishi@gmail.com",
    "profileImageUrl":"dfgfdgdf"
}